[package]
name = "flexispot-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.3"
itertools = "0.13.0"
log = "0.4.21"
rppal = "0.18.0"
rumqttc = "0.24.0"
